//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReplicateOracleDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public decimal ID { get; set; }
        public string NAME { get; set; }
        public decimal PRICE { get; set; }
        public decimal MESURE_ID { get; set; }
        public decimal VENDOR_ID { get; set; }
    
        public virtual MEASURE MEASURE { get; set; }
        public virtual VENDOR VENDOR { get; set; }
    }
}
